@startuml
autonumber 1 "[0.0]"
title ApplicationContext 创建过程

SpringApplication -> SpringApplication : createApplicationContext\n创建上下文对象

SpringApplication -> AnnotationConfigEmbeddedWebApplicationContext : BeanUtils.instantiate(contextClass) \n创建实例\nAnnotationConfigEmbeddedWebApplicationContext()

AnnotationConfigEmbeddedWebApplicationContext --> AnnotatedBeanDefinitionReader : 初始化AnnotatedBeanDefinitionReader\n(BeanDefinitionRegistry registry)

AnnotatedBeanDefinitionReader -> AnnotatedBeanDefinitionReader:getOrCreateEnvironment\n(BeanDefinitionRegistry registry)

@enduml