jedis:
  pool:
    config:
      maxTotal: 300
      maxIdle: 50
      minIdle: 20
      maxWaitMillis: 3000
    host: dev.redis.java110.com
    port: 6379
    timeout: 3000
    password: hc

server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8

java110:
  community-service: community-service
  acct-service: acct-service
  user-service: user-service
  store-service: store-service
  common-service: common-service
  job-service: job-service
  fee-service: fee-service
  report-service: report-service
  dev-service: dev-service
  oa-service: oa-service

spring:
  profiles:
    active: share
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: boot-service
  redis:
    database: 0
    host: dev.redis.java110.com
    port: 6379
    password: hc
    pool:
      max-active: 300
      max-wait: 3000
      max-idle: 50
      min-idle: 20
      timeout: 0
  activiti:
    database-schema-update: false

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000

#============== kafka ===================
kafka:
  consumer:
    zookeeper:
      connect: dev.zk.java110.com:2181
    servers: dev.kafka.java110.com:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: test
    group:
      id: communityBusinessStatus
    concurrency: 10

  producer:
    zookeeper:
      connect: dev.zk.java110.com:2181
    servers: dev.kafka.java110.com:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960